/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: nigromancer (https://sketchfab.com/nigromancer)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/snow-mountain-28d511ddb8624eee9684e93824e543f5
title: Snow Mountain
*/

import * as THREE from "three";
import {
  useRef,
  useMemo,
  useContext,
  createContext,
  useEffect,
  RefObject,
} from "react";
import { useGLTF, Merged } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Group, Mesh, SphereBufferGeometry, Vector3 } from "three";
import { WORLD_SIZE } from "../Scene";
import { getRandomNumber, pickRandomIntFromInterval } from "../utils";

type GLTFResult = GLTF & {
  nodes: {
    SM_Generic_Mountains_Snow_01_SM_Generic_Mountains_Snow_01_PolygonTown_01_A_0: THREE.Mesh;
  };
  materials: {
    SM_Generic_Mountains_Snow_01_PolygonTown_01_A: THREE.MeshStandardMaterial;
  };
};

const context = createContext(undefined);
// @ts-ignore
export function MountainInstances({ children, ...props }) {
  const { nodes } = useGLTF(
    "/models/Mountain/scene-transformed.glb"
  ) as GLTFResult;
  const instances = useMemo(
    () => ({
      SMGenericMountainsSnowSMGenericMountainsSnowPolygonTownA:
        nodes.SM_Generic_Mountains_Snow_01_SM_Generic_Mountains_Snow_01_PolygonTown_01_A_0,
    }),
    [nodes]
  );
  return (
    <Merged meshes={instances} {...props}>
      {/*
      // @ts-ignore */}
      {(instances) => (
        <context.Provider value={instances} children={children} />
      )}
    </Merged>
  );
}

export function Mountain({
  v3,
  earthRef,
}: {
  v3: Vector3;
  earthRef?: RefObject<Mesh<SphereBufferGeometry>>;
}) {
  const instances = useContext(context);
  const groupRef = useRef<Group>();
  const scale = useMemo(() => pickRandomIntFromInterval(5, 10) * 0.002, []);

  useEffect(() => {
    if (!earthRef?.current || !groupRef?.current) {
      return;
    }

    groupRef.current.position.setFromSphericalCoords(
      WORLD_SIZE - 0.01,
      v3.y,
      v3.x
    );
    groupRef.current.lookAt(earthRef.current.position);
  }, [earthRef, v3]);

  return (
    <group ref={groupRef}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={scale} dispose={null}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group rotation={[Math.PI / 2, 0, 0]}>
              {/*
              // @ts-ignore */}
              <instances.SMGenericMountainsSnowSMGenericMountainsSnowPolygonTownA />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Mountain/scene-transformed.glb");
